version: '3'
services:
  occalc-back:
    build: .
    depends_on:
      - occalc-db
    container_name: occalc-back
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
  occalc-db:
    image: "postgres:13.4"
    container_name: occalc-db
    environment: 
      POSTGRES_PASSWORD: dev_password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
volumes:
  db-data: